name: blimp
channels:
  - ilastik-forge
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy>=1
  - ilastikrag>=0.1.4
  - vigra=1.12.1
  - fastfilters
  - nifty
  - affogato
  - scikit-learn<=1.6.1
  - scikit-image
  - h5py
  - zarr 2.*
  - fsspec
  - aiohttp
  - pandas>=2
  - tqdm
  - numba
  - pytest
  - pip
  - setuptools>=61
  - wheel
  - python-elf
  - requests
  - nomkl
  - libblas=*=*openblas
  - liblapack=*=*openblas
  - libcblas=*=*openblas
