name: blockwise-mc
channels:
  - ilastik-forge/label/patched-2
  - ilastik-forge
  - conda-forge
  - nodefaults
dependencies:
  - python
  - numpy>=1
  - ilastikrag>=0.1.4
  - vigra=1.12.1
  - nifty
  - affogato
  - scikit-learn<=1.6.1
  - scikit-image
  - h5py
  - zarr>=2,<4
  - fsspec
  - aiohttp
  - pandas>=2
  - tqdm
  - numba
  - pytest
  - pip
  # claude: use pip-override below. user: remove pip section and include python-elf from conda instead
  # - python-elf
  - requests
  - pip:
    - ./libs/elf@b58e4c83
